module.exports = {
  BASE_URL: 'localhost:3000/',
  HOME: '/',
  CUSTOMERS: '/',
  CUSTOMERS_LOGIN: '/login',
  CUSTOMERS_PORTAL: '/portal',
  CUSTOMERS_PORTAL_GENERAL_SETTINGS: '/portal/generalSettings',
  CUSTOMERS_PORTAL_COMPANY_SETTINGS: '/portal/companySettings',
  CUSTOMERS_PORTAL_COMMUNICATION_SETTINGS: '/portal/communicationSettings',
  CUSTOMERS_PORTAL_CREATE_VEHICLE_OWNER: '/portal/createVehicleOwner',
  CUSTOMERS_PORTAL_READ_VEHICLE_OWNER: '/portal/readVehicleOwner',
  CUSTOMERS_PORTAL_CREATE_VEHICLE_TYPE: 'portal/createVehicleType',
  CUSTOMERS_PORTAL_READ_VEHICLE_TYPE: 'portal/readVehicleType',
  CUSTOMERS_PORTAL_CREATE_VEHICLES_VEHICLE: 'portal/createVehicleVehicle',
  CUSTOMERS_PORTAL_READ_VEHICLES_VEHICLE: 'portal/readVehicleVehicle',
  CUSTOMERS_PORTAL_CREATE_DRIVERS_DRIVER: 'portal/createDriverDriver',
  CUSTOMERS_PORTAL_READ_DRIVERS_DRIVER: 'portal/readDriverDriver',
  CUSTOMERS_PORTAL_CREATE_EMPLOYEE_SHIFT: 'portal/createEmployeeShift',
  CUSTOMERS_PORTAL_READ_EMPLOYEE_SHIFT: 'portal/readEmployeeShift',
  CUSTOMERS_PORTAL_CREATE_CUSTOMERS_CUSTOMER: 'portal/createCustomerCustomer',
  CUSTOMERS_PORTAL_READ_CUSTOMERS_CUSTOMER: 'portal/readCustomerCustomer',
  CUSTOMERS_PORTAL_CREATE_ADDRESSES_POSTAL_CODE: 'portal/createAddressesPostalCode',
  CUSTOMERS_PORTAL_READ_ADDRESSES_POSTAL_CODE: 'portal/readAddressesPostalCode',
  CUSTOMERS_PORTAL_CREATE_ADDRESSES_ADDRESS: 'portal/createAddressesAddress',
  CUSTOMERS_PORTAL_READ_ADDRESSES_ADDRESS: 'portal/readAddressesAddress',
  CUSTOMERS_PORTAL_CREATE_ADDRESSES_AREA: 'portal/createAddressesArea',
  CUSTOMERS_PORTAL_READ_ADDRESSES_AREA: 'portal/readAddressesArea',
}